#!/bin/sh

# Common configuration options
. $(dirname $0)/../../common/proxy
. $(dirname $0)/../../common/locales
. $(dirname $0)/../../common/distro

# Configure build tree
lb config noauto \
	--ignore-system-defaults \
	--mode=debian \
	--distribution="${DEBIAN_RELEASE}" \
	--archive-areas "main contrib non-free non-free-firmware" \
	--backports "true" \
	--mirror-bootstrap ${MIRROR}/debian \
	--mirror-chroot ${MIRROR}/debian \
	--mirror-chroot-security ${MIRROR}/security \
	--architecture amd64 \
	--debian-installer live \
	--binary-images iso-hybrid \
	--system=live \
	--bootappend-live "boot=live config ${BOOTOPTS}" \
	--apt-recommends true \
	--memtest memtest86+ \
	--image-name 'ronolinux-desktop-snapshot-binary' \
	--iso-volume="ronolinux-${DEBIAN_RELEASE}" \
	--iso-application="Ronolinux Desktop ${DEBIAN_RELEASE}" \
	--iso-preparer="Ronoaldo Consulting" \
	--iso-publisher="Ronoaldo Consulting" \
	--clean \
	"${@}"
