#!/bin/sh

# Includes default functions
. $(dirname $0)/../../common/proxy
. $(dirname $0)/../../common/locales

# Current release
export release="precise"

# Build options
lb config noauto \
	--mode=ubuntu \
	--distribution="$release" \
	--keyring-packages="ubuntu-keyring" \
	--archive-areas="main restricted universe multiverse" \
	--mirror-bootstrap=$mirror/ubuntu \
	--mirror-chroot-security=$mirror/ubuntu-security \
	--architecture=i386 \
	--initramfs=live-boot \
	--binary-images=iso-hybrid \
	--bootloader=grub2 \
	--debian-installer=live \
	--ignore-system-defaults \
	--iso-application="Ubuntu Minimal" \
	--iso-preparer="Ronoaldo Consulting" \
	--iso-publisher="Ronoaldo Consulting" \
	--iso-volume="Ubuntu_Minimal" \
	--memtest=none \
	--system=live \
	--clean \
	"${@}"
