#!/bin/sh

export mirror="http://localhost:9999"
export release="precise"

export locale="pt_BR.UTF-8"
export kb="br"
export kbvariant="abnt2"

# Default values #
export bootopts="locales=$locale keyboard-layouts=$kb keyboard-variants=$kbvariant"

lb config noauto \
	--mode=ubuntu \
	--distribution "$release" --keyring-packages="ubuntu-keyring" \
	--architecture i386 --linux-flavours generic \
	--archive-areas "main restricted universe multiverse" \
	--mirror-bootstrap $mirror/ubuntu \
	--mirror-chroot-security $mirror/ubuntu-security \
	--debian-installer live \
	--bootappend-live "boot=live config $bootopts" \
	--apt-indices false --apt-recommends false --memtest none \
	--initramfs casper  \
	"${@}"
