#!/bin/sh

# Common configuration options
. $(dirname $0)/../../common/proxy
. $(dirname $0)/../../common/locales

# Release
export release="jessie"

# Configure build tree
lb config noauto \
	--ignore-system-defaults \
	--mode=debian \
	--distribution="$release" \
	--archive-areas "main contrib non-free" \
	--mirror-bootstrap $mirror/debian \
	--mirror-chroot-security $mirror/security \
	--architecture amd64 \
	--debian-installer live \
	--binary-images iso-hybrid \
	--system=live \
	--bootappend-live "boot=live config $bootopts" \
	--apt-indices false \
	--apt-recommends false \
	--memtest memtest86+ \
	--image-name 'ronolinux-developer-snapshot-binary' \
	--iso-application="Developer Desktop" \
	--iso-preparer="Ronoaldo Consulting" \
	--iso-publisher="Ronoaldo Consulting" \
	--iso-volume="Ronolinux_Developer" \
	--clean \
	"${@}"
