#!/bin/bash

# Common configuration for all custom builds

# Use the tools/configure-local-apt-cache script to configure
# a local repository cache - Usefull for speed up rebuilds
export mirror="http://localhost:9999"

# Locales and setup
export locale="pt_BR.UTF-8"
export kb="br"
export kbvariant="abnt2"

# Default values #
export bootopts="locales=$locale "
export bootopts="keyboard-layouts=$kb keyboard-variants=$kbvariant"
