#!/bin/bash

# Locales and setup
export locale="pt_BR.UTF-8"
export kb="br"
export kbvariant="abnt2"

# Default values #
export bootopts="locales=$locale "
export bootopts="keyboard-layouts=$kb keyboard-variants=$kbvariant"
