#!/bin/bash

# Builds all images automatically.

basedir="$(readlink -f $(dirname $0)/..)"
cd $basedir

buildstamp="$(date '+%Y%m%d-%H%M%S')"

# Informational messages
info() {
	echo "[buildd] $(date '+%Y-%m-%d %H:%M:%S'): $@"
}

# Run lb build on the current directory.
build_iso() {
	if [ -n "$DRY_RUN" ] ; then
		info "* Dry run only ... exiting"
		return 0
	fi
	sudo lb clean --purge && lb config && sudo lb build
}

# Publish the snapshot iso to sourceforge project files
deploy_snapshot() {
	info Releasing snapshot file $1 as $2 on frs.sourceforge.net ...
	if [ -n "$DRY_RUN" ] ; then
		info "* Dry run, skipping upload"
		return 0
	fi
	rsync -e ssh $1 ronoaldo@frs.sourceforge.net:/home/frs/project/ronolinux/snapshots/$2
}

# Main
FLAVORS=""
while [ $# -gt 0 ]; do
	case $1 in
		--deploy|--publish)
			export PUBLISH="1"
		;;
		*)
			export FLAVORS="$FLAVORS $1"
		;;
	esac
	shift
done
FLAVORS="${FLAVORS:-desktop education}"

# Loop over each flavor and build them
info
info "Building flavors: $FLAVORS ..."
info

for flavor in $FLAVORS ; do
	if ! [ -d $basedir/$flavor ] ; then
		echo "*** Unable to find $basedir/$flavor. "
		exit 1
	fi
	cd ${basedir}/$flavor

	info "*****"
	info "Building $flavor ..."
	info "*****"

	if build_iso ; then
		info "$flavor build done"
		if [ -n "$PUBLISH" ]; then
			info "Releasing snapshot files for $flavor ..."
			for f in ronolinux-$flavor-snapshot-binary-amd64.* ; do
				deploy_snapshot $f $f
			done
			deploy_snapshot build.log ronolinux-$flavor-snapshot-binary-amd64.log
		else
			info "Skipping release of snapshots"
		fi
	else
		info "Build of $flavor failed."
	fi

	cd $basedir 
	info "Done"
	info
done

